/**
 * Created by zlf on 2017/7/25.
 */
define(function(require,exports,module){
    module.exports={
        list1:[
            {
                title:"[微笑]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_smile.png"
            },
            {
                title:"[憨笑]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_smilefatuously.png"
            },
            {
                title:"[偷笑]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_giggle.png"
            },
            {
                title:"[坏笑]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_grin.png"
            },
            {
                title:"[色]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_se.png"
            },
            {
                title:"[鼓掌]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_handclap.png"
            },
            {
                title:"[龇牙]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_Laugh.png"
            },
            {
                title:"[亲亲]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_kiss.png"
            },
            {
                title:"[调皮]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_naughty.png"
            },
            {
                title:"[可怜]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_poor.png"
            },
            {
                title:"[害羞]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_shy.png"
            },
            {
                title:"[得意]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_proud.png"
            },
            {
                title:"[撇嘴]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_piezui.png"
            },
            {
                title:"[大哭]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_crying.png"
            },
            {
                title:"[咒骂]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_cursing.png"
            },
            {
                title:"[愤怒]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_anger.png"
            },
            {
                title:"[汗]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_sweat.png"
            },
            {
                title:"[尴尬]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_awkward.png"
            },
            {
                title:"[惊恐]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_panic.png"
            },
            {
                title:"[委屈]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_grievance.png"
            },
            {
                title:"[抓狂]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_crazy.png"
            },
            {
                title:"[右哼哼]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_righthum.png"
            },
            {
                title:"[左哼哼\]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_leftscorn.png"
            },
            {
                title:"[吐]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_vomit.png"
            },
            {
                title:"[哈欠\]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_yawn.png"
            },
            {
                title:"[睡]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_sleep.png"
            },
            {
                title:"[嘘]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_hush.png"
            },
            {
                title:"[疑问]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_doubt.png"
            },
            {
                title:"[不语]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_mute.png"
            },
            {
                title:"[衰]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_failure.png"
            },
            {
                title:"[拥抱]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_hug.png"
            },
            {
                title:"[敲]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_beat.png"
            },
            {
                title:"[晕]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_halo.png"
            },
            {
                title:"[奋斗]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_struggle.png"
            },
            {
                title:"[再见]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_bye.png"
            },
            {
                title:"[馋]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_greedy.png"
            },
            {
                title:"[菜刀]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_knife.png"
            },
            {
                title:"[猪头]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_pig.png"
            },
            {
                title:"[便便]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_defecate.png"
            },
            {
                title:"[强]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_strong.png"
            },
            {
                title:"[弱]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_weak.png"
            },
            {
                title:"[握手]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_handshake.png"
            },
            {
                title:"[胜利]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_yeah.png"
            },
            {
                title:"[抱拳]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_baoquan.png"
            },
            {
                title:"[闪电]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_lightning.png"
            },
            {
                title:"[炸弹]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_bomb.png"
            },
            {
                title:"[乒乓]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_pingpong.png"
            },
            {
                title:"[篮球]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_basketball.png"
            },
            {
                title:"[足球]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_football.png"
            },
            {
                title:"[蛋糕]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_cake.png"
            },
            {
                title:"[太阳]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_sun.png"
            },
            {
                title:"[示爱]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_lip.png"
            },
            {
                title:"[玫瑰]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_rose.png"
            },
            {
                title:"[凋谢]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_fade.png"
            },
            {
                title:"[爱心]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_love.png"
            },
            {
                title:"[心碎]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_heartbreak.png"
            },
            {
                title:"[咖啡]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_cofee.png"
            },
            {
                title:"[西瓜]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_watermelon.png"
            },
            {
                title:"[月亮]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_moon.png"
            },
            {
                title:"[啤酒]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_bear.png"
            }
             ],
        list2:[
            {
                title:"[:OK]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang1_ok.png"
            },
            {
                title:"[:报歉]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang2_baoqian.png"
            },
            {
                title:"[:悲伤]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang3_beishang.png"
            },
            {
                title:"[:财神]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang4_caishen.png"
            },
            {
                title:"[:发火]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang5_fahuo.png"
            },
            {
                title:"[:姑姑]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang6_gugu.png"
            },
            {
                title:"[:鬼脸]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang7_guilian.png"
            },
            {
                title:"[:滚]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang8_gun.png"
            },
            {
                title:"[:汗]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang9_han.png"
            },
            {
                title:"[:哼]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang10_heng.png"
            },
            {
                title:"[:花心]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang11_huaxin.png"
            },
            {
                title:"[:举个例子]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang12_jugelizi.png"
            },
            {
                title:"[:哭]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang13_ku.png"
            },
            {
                title:"[:猫]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang14_mao.png"
            },
            {
                title:"[:鸟叔]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang15_niaoshu.png"
            },
            {
                title:"[:潜水]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang16_qianshui.png"
            },
            {
                title:"[:撒花]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang17_sahua.png"
            },
            {
                title:"[:色]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang18_se.png"
            },
            {
                title:"[:手指右上]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang19_shouzhiyoushang.png"
            },
            {
                title:"[:睡觉]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang20_shuijiao.png"
            },
            {
                title:"[:送礼物]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang21_songliwu.png"
            },
            {
                title:"[:吐舌头]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang22_tushetou.png"
            },
            {
                title:"[:万圣节]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang23_wanshengjie.png"
            },
            {
                title:"[:围观]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang24_weiguan.png"
            },
            {
                title:"[:我好美]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang25_wohaomei.png"
            },
            {
                title:"[:无聊]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang26_wuliao.png"
            },
            {
                title:"[:吸血鬼]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang27_xixuegui.png"
            },
            {
                title:"[:小怪兽]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang28_xiaoguaishou.png"
            },
            {
                title:"[:小太阳]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang29_xiaotaiyang.png"
            },
            {
                title:"[:赞]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang30_zan.png"
            },
            {
                title:"[:震惊]",
                src:"http://www.xcar.com.cn/bbs/images/smilies/phiz_xjiang31_zhenjing.png"
            }
        ]
    }

});
